---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-apiserver-apiserver
  namespace: demo-apiserver
  labels:
    api: demo-apiserver
    apiserver: "true"
spec:
  selector:
    matchLabels:
      api: demo-apiserver
      apiserver: "true"
  replicas: 1
  template:
    metadata:
      labels:
        api: demo-apiserver
        apiserver: "true"
    spec:
      containers:
      - name: apiserver
        image: demo.harbor.com/aggregator/demo-apiserver:latest
        volumeMounts:
        - name: apiserver-certs
          mountPath: /apiserver.local.config/certificates
          readOnly: true
        command:
        - "./apiserver"
        args:
        - "--etcd-servers=http://etcd-svc:2379"
        - "--tls-cert-file=/apiserver.local.config/certificates/tls.crt"
        - "--tls-private-key-file=/apiserver.local.config/certificates/tls.key"
        - "--audit-log-path=-"
        - "--feature-gates=APIPriorityAndFairness=false"
        - "--audit-log-maxage=0"
        - "--audit-log-maxbackup=0"
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 30Mi
      volumes:
      - name: apiserver-certs
        secret:
          secretName: demo-apiserver
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: demo-apiserver
  namespace: demo-apiserver
  labels:
    api: demo-apiserver
    apiserver: "true"
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURyekNDQXBlZ0F3SUJBZ0lJQWJBbmtoUjNtY3N3RFFZSktvWklodmNOQVFFTEJRQXdiakVMTUFrR0ExVUUKQmhNQ2RXNHhDekFKQmdOVkJBZ01Bbk4wTVFvd0NBWURWUVFIREFGc01Rb3dDQVlEVlFRS0RBRnZNUXN3Q1FZRApWUVFMREFKdmRURXRNQ3NHQTFVRUF3d2taR1Z0YnkxaGNHbHpaWEoyWlhJdFkyVnlkR2xtYVdOaGRHVXRZWFYwCmFHOXlhWFI1TUI0WERUSXpNRGN4TURBMk5UZ3dNVm9YRFRNek1EY3dOekEyTlRnd01Wb3dMREVxTUNnR0ExVUUKQXhNaFpHVnRieTFoY0dselpYSjJaWEl1WkdWdGJ5MWhjR2x6WlhKMlpYSXVjM1pqTUlJQklqQU5CZ2txaGtpRwo5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBdE9GS1pLS1U5VFNiYk9xNHJ1QkFTZ1RPZFJCY3o3ekFIUUl4CndEN3ljY0RHOTRMa25jcUM5UGs5anFtV3JIazByZ2lxVEdiMkJpUlNlcTZKWkpPSFVoNWNJMFlUVW5QUW14TXUKUi8yWW01NE9VdzRkMy84S2JBbXN6bEJOb3loNFRsbVBSNFE2RTdNYTlVMmhhaEtBbUt3WWhwRnVXWVh4SnRKNAoyQklkYjdyUkM5ckZLaU5tWGFNRVlyS1l6aFNWWlFlRkp2dklmckRtOG1JbzllMUZjZEtnaXpVd09iQnIweVZVCmo3b3VaVVlaWU5ia0VJYm5zcTc4WDdnMFNFT3RzdVdMNVVjMlY4OERKTnBXWmNrZ3pvZk9iT3QyY2dEU1ROUVYKcTZUcDgrZHZFTTVkeEdMcy9FNkViMmlTd1FyRjZwNDRaQ3Q3eHRmMitlaDRKUzhSNFFJREFRQUJvNEdTTUlHUApNQTRHQTFVZER3RUIvd1FFQXdJRm9EQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUhBd0l3Ckh3WURWUjBqQkJnd0ZvQVVsN21IRmYxNDhXU3hTTXQ4QTIrd01CUTllemd3UFFZRFZSMFJCRFl3TklJSmJHOWoKWVd4b2IzTjBnaUZrWlcxdkxXRndhWE5sY25abGNpNWtaVzF2TFdGd2FYTmxjblpsY2k1emRtT0hCSDhBQUFFdwpEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSXUzc2V0UkxRRG5CZEFMOGY1Z3J2OXllM1F6VHIxZjBMK1BRR0k1Cml4S3VQQy82ck5jeGQ5eHlSa0VyYmVoME1VdENOWHI3eGlqelVJN3I0MWZMMFEwSXZoSG1nd2c0OFRHdm5xa2UKZUJ3OWdVSmNoWitERldnSW1KRWZUNEpjdmc3SEZVMXFRYXlsUzB1NUdNdEZqT0dzdVFxMzlOc2ZPRWpxdHhxMgppUWV4Um1GQUFCOXZNMmJwcWhhTEMvK2hhWk13dGhWSW5lMnBWYW5NZ0d5WlFqekpUS3NiTWRZd3NSN0I1Szk3CkRSRFBETVg3cnJPa3N2NjRoZjlQTDk2ZFU0MVJDdW1hVjFIbHpJelg4OUxkbmxyaGhoaE9qamRZMll1SnR0bE8KUmlRa2FCZm43Q09PTHAxaTdRUHI5MS9NZnQ2bEtrTyszSTMrb2dqa290ekJzV0U9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBdE9GS1pLS1U5VFNiYk9xNHJ1QkFTZ1RPZFJCY3o3ekFIUUl4d0Q3eWNjREc5NExrCm5jcUM5UGs5anFtV3JIazByZ2lxVEdiMkJpUlNlcTZKWkpPSFVoNWNJMFlUVW5QUW14TXVSLzJZbTU0T1V3NGQKMy84S2JBbXN6bEJOb3loNFRsbVBSNFE2RTdNYTlVMmhhaEtBbUt3WWhwRnVXWVh4SnRKNDJCSWRiN3JSQzlyRgpLaU5tWGFNRVlyS1l6aFNWWlFlRkp2dklmckRtOG1JbzllMUZjZEtnaXpVd09iQnIweVZVajdvdVpVWVpZTmJrCkVJYm5zcTc4WDdnMFNFT3RzdVdMNVVjMlY4OERKTnBXWmNrZ3pvZk9iT3QyY2dEU1ROUVZxNlRwOCtkdkVNNWQKeEdMcy9FNkViMmlTd1FyRjZwNDRaQ3Q3eHRmMitlaDRKUzhSNFFJREFRQUJBb0lCQUF0UGN4bHIyU2lrQzN2NgpDV1pWKzI4bGNjdDhKSEdRK2VwV2NzbjBwYkJiUDVYR2g0a2VXcVg2MTlDTjVqQU92QzZOdUNoaTM4dHVoZ0hKCjNDbC8yQnhZYmFaL0FVSk1uNlN5eEZnWUVXelpxMGVpUUZmN1dLbDh5V04xUGdXUHlFWU43NW1uT1FKMlZwODAKSlgyK2ZuQU5ndE1YVVBFa0lQb3Vld1AzemdOb2JoWGliVTU2NmNVV3JYTFJJTmdFWmhtc2FZUG5nNklIZktvbgpDQXVRc0x3RWtsRVZhWXZ3UjBXWnhNSEJ3MzdaMStlakh4b3NmR0xGV0Q5UkxTT2R1bCtQNHZFZGNPcEtMS1U3ClkrUmNDWVA1SWlkSUI5dWxzcnJLc0EvZ0VrS3FsQlh1cUIyc2JPd1dDTnBtVmVNOEo1Rzh1TEhOZDhicFR1MjQKR0U3Q0UyRUNnWUVBdzh6K3RnT1JCNTFzd2twMmNUMjA4NHhUbTZoaXNtUU9rcHo3cmhvQzF0TUpCSnV1Q1pvYwpOOUpCeC92RXIwckJlODNPajVjM1p0dDF3d004b0VzNnZQTWM3RWdNSHpvbHJiNUtTbExpVGFvM3dKa0l2U1dKCjRjTTBBbk1oWEpXV1YzeDFOQVdEWmNKMzRNVTQyK2RUU3p1MlgzNVF0WThTMmZ1SzhKQ09BU1VDZ1lFQTdIM3IKK2hxd1Z3RW0rMmtvejJrUXFkYUwrM2RKaDNQRlJOMGFZVFdUZExLeU9ZRlpRa2FDSXVUMlpJQ1BsODJZenZVcgpwRHFkN2hWMXdZRGdRQnJYVng1WXBZeDNEeUwzUExNbDUxdCs0aUpGN1JGWUdHVzY0Z09hSmswZTE4azJUdVZECks3bFhqckM0ZUdpazQ1citwT3RibzRRa1k3NEM5OUtTb0lQZEJ3MENnWUJ1MUZJNDVMdnErNGpjVVJuSjc0dkYKYitERGN3U3F4VWdhWlJGdzh2ZzRjU3ZobDkxalFnQkcrSlNUaGtkR2thSURXZk5hQTlZd09uamw4YWNYZEgzRApCam1RNVJjM2RjcHVGaEFuRWROVzhzcXNFZk9JWFA4Mjh5ODFVOFhHaWtXWEw3T0h4cmNobW5vUW1KSWVwMG5XCmcrNHZEMmpQM0RSbmZxS2VtTFJJb1FLQmdRQ1BIdzNteUt3Ym0zanFBaFJPb2JrUjcrTzdoYytjQi9aRTNNS1EKUGdwRlA3Z1lrUzFocktZcFZBUEJnd1Jqekd0RUpLQUt2ZWJDSlg2a1lzaFVRMm83TVFSWS9BODV1K0dBZkxMZAp0ME9zdXkweWNhS3M4VFFPZ0R1VUhtd2lENFdzYlpjZktRWFNOeVVNeWRld1h5Ym95Lzhqa0Y4dGRkcjUvQmY4CnlKREZLUUtCZ1FDUzFPeTFFTTgwcHc2SDdNVWVERW40dVpmK2ZQL2gwTGw3NS94cVV2QjNZTC80Y1Nwc2lSYXYKRmREKzFROWtLOWR6Q3gxZDJvb1lsdmhoSjlGaTdaMTRzMzF0VEpqaTRUTVErNENrMjd1bkZlKzZaeE5zcVdBdgpQOS94NTF3NXlFdW1nSUxOQitjSng2TGlPZjVudHRxSDVwOVdsQXEzTUx2STlhVzNyTHZoUHc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: v1
kind: Service
metadata:
  name: demo-apiserver
  namespace: demo-apiserver
  labels:
    api: demo-apiserver
    apiserver: "true"
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    api: demo-apiserver
    apiserver: "true"
