---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-apiserver-controller
  namespace: demo-apiserver
  labels:
    api: demo-apiserver
    controller: "true"
spec:
  selector:
    matchLabels:
      api: demo-apiserver
      controller: "true"
  replicas: 1
  template:
    metadata:
      labels:
        api: demo-apiserver
        controller: "true"
    spec:
      containers:
      - name: controller
        image: demo.harbor.com/aggregator/demo-apiserver:latest
        command:
        - "./controller-manager"
        args:
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 100m
            memory: 300Mi
      volumes:
      - name: apiserver-certs
        secret:
          secretName: demo-apiserver
