//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	unsafe "unsafe"

	tiankuixing "cangbinggu.io/buliangren/pkg/apis/tiankuixing"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*UpdateConfig)(nil), (*tiankuixing.UpdateConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_UpdateConfig_To_tiankuixing_UpdateConfig(a.(*UpdateConfig), b.(*tiankuixing.UpdateConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*tiankuixing.UpdateConfig)(nil), (*UpdateConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_tiankuixing_UpdateConfig_To_v1_UpdateConfig(a.(*tiankuixing.UpdateConfig), b.(*UpdateConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*UpdateConfigList)(nil), (*tiankuixing.UpdateConfigList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_UpdateConfigList_To_tiankuixing_UpdateConfigList(a.(*UpdateConfigList), b.(*tiankuixing.UpdateConfigList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*tiankuixing.UpdateConfigList)(nil), (*UpdateConfigList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_tiankuixing_UpdateConfigList_To_v1_UpdateConfigList(a.(*tiankuixing.UpdateConfigList), b.(*UpdateConfigList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*UpdateConfigSpec)(nil), (*tiankuixing.UpdateConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_UpdateConfigSpec_To_tiankuixing_UpdateConfigSpec(a.(*UpdateConfigSpec), b.(*tiankuixing.UpdateConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*tiankuixing.UpdateConfigSpec)(nil), (*UpdateConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_tiankuixing_UpdateConfigSpec_To_v1_UpdateConfigSpec(a.(*tiankuixing.UpdateConfigSpec), b.(*UpdateConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*UpdateConfigStatus)(nil), (*tiankuixing.UpdateConfigStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_UpdateConfigStatus_To_tiankuixing_UpdateConfigStatus(a.(*UpdateConfigStatus), b.(*tiankuixing.UpdateConfigStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*tiankuixing.UpdateConfigStatus)(nil), (*UpdateConfigStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_tiankuixing_UpdateConfigStatus_To_v1_UpdateConfigStatus(a.(*tiankuixing.UpdateConfigStatus), b.(*UpdateConfigStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1_UpdateConfig_To_tiankuixing_UpdateConfig(in *UpdateConfig, out *tiankuixing.UpdateConfig, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_UpdateConfigSpec_To_tiankuixing_UpdateConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_UpdateConfigStatus_To_tiankuixing_UpdateConfigStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_UpdateConfig_To_tiankuixing_UpdateConfig is an autogenerated conversion function.
func Convert_v1_UpdateConfig_To_tiankuixing_UpdateConfig(in *UpdateConfig, out *tiankuixing.UpdateConfig, s conversion.Scope) error {
	return autoConvert_v1_UpdateConfig_To_tiankuixing_UpdateConfig(in, out, s)
}

func autoConvert_tiankuixing_UpdateConfig_To_v1_UpdateConfig(in *tiankuixing.UpdateConfig, out *UpdateConfig, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_tiankuixing_UpdateConfigSpec_To_v1_UpdateConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_tiankuixing_UpdateConfigStatus_To_v1_UpdateConfigStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_tiankuixing_UpdateConfig_To_v1_UpdateConfig is an autogenerated conversion function.
func Convert_tiankuixing_UpdateConfig_To_v1_UpdateConfig(in *tiankuixing.UpdateConfig, out *UpdateConfig, s conversion.Scope) error {
	return autoConvert_tiankuixing_UpdateConfig_To_v1_UpdateConfig(in, out, s)
}

func autoConvert_v1_UpdateConfigList_To_tiankuixing_UpdateConfigList(in *UpdateConfigList, out *tiankuixing.UpdateConfigList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]tiankuixing.UpdateConfig)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_UpdateConfigList_To_tiankuixing_UpdateConfigList is an autogenerated conversion function.
func Convert_v1_UpdateConfigList_To_tiankuixing_UpdateConfigList(in *UpdateConfigList, out *tiankuixing.UpdateConfigList, s conversion.Scope) error {
	return autoConvert_v1_UpdateConfigList_To_tiankuixing_UpdateConfigList(in, out, s)
}

func autoConvert_tiankuixing_UpdateConfigList_To_v1_UpdateConfigList(in *tiankuixing.UpdateConfigList, out *UpdateConfigList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]UpdateConfig)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_tiankuixing_UpdateConfigList_To_v1_UpdateConfigList is an autogenerated conversion function.
func Convert_tiankuixing_UpdateConfigList_To_v1_UpdateConfigList(in *tiankuixing.UpdateConfigList, out *UpdateConfigList, s conversion.Scope) error {
	return autoConvert_tiankuixing_UpdateConfigList_To_v1_UpdateConfigList(in, out, s)
}

func autoConvert_v1_UpdateConfigSpec_To_tiankuixing_UpdateConfigSpec(in *UpdateConfigSpec, out *tiankuixing.UpdateConfigSpec, s conversion.Scope) error {
	out.ImageName = in.ImageName
	out.ConfigMapName = in.ConfigMapName
	out.DeploymentName = in.DeploymentName
	out.Counts = in.Counts
	return nil
}

// Convert_v1_UpdateConfigSpec_To_tiankuixing_UpdateConfigSpec is an autogenerated conversion function.
func Convert_v1_UpdateConfigSpec_To_tiankuixing_UpdateConfigSpec(in *UpdateConfigSpec, out *tiankuixing.UpdateConfigSpec, s conversion.Scope) error {
	return autoConvert_v1_UpdateConfigSpec_To_tiankuixing_UpdateConfigSpec(in, out, s)
}

func autoConvert_tiankuixing_UpdateConfigSpec_To_v1_UpdateConfigSpec(in *tiankuixing.UpdateConfigSpec, out *UpdateConfigSpec, s conversion.Scope) error {
	out.ImageName = in.ImageName
	out.ConfigMapName = in.ConfigMapName
	out.DeploymentName = in.DeploymentName
	out.Counts = in.Counts
	return nil
}

// Convert_tiankuixing_UpdateConfigSpec_To_v1_UpdateConfigSpec is an autogenerated conversion function.
func Convert_tiankuixing_UpdateConfigSpec_To_v1_UpdateConfigSpec(in *tiankuixing.UpdateConfigSpec, out *UpdateConfigSpec, s conversion.Scope) error {
	return autoConvert_tiankuixing_UpdateConfigSpec_To_v1_UpdateConfigSpec(in, out, s)
}

func autoConvert_v1_UpdateConfigStatus_To_tiankuixing_UpdateConfigStatus(in *UpdateConfigStatus, out *tiankuixing.UpdateConfigStatus, s conversion.Scope) error {
	out.LastUpdate = in.LastUpdate
	out.ReconcileCounts = in.ReconcileCounts
	return nil
}

// Convert_v1_UpdateConfigStatus_To_tiankuixing_UpdateConfigStatus is an autogenerated conversion function.
func Convert_v1_UpdateConfigStatus_To_tiankuixing_UpdateConfigStatus(in *UpdateConfigStatus, out *tiankuixing.UpdateConfigStatus, s conversion.Scope) error {
	return autoConvert_v1_UpdateConfigStatus_To_tiankuixing_UpdateConfigStatus(in, out, s)
}

func autoConvert_tiankuixing_UpdateConfigStatus_To_v1_UpdateConfigStatus(in *tiankuixing.UpdateConfigStatus, out *UpdateConfigStatus, s conversion.Scope) error {
	out.LastUpdate = in.LastUpdate
	out.ReconcileCounts = in.ReconcileCounts
	return nil
}

// Convert_tiankuixing_UpdateConfigStatus_To_v1_UpdateConfigStatus is an autogenerated conversion function.
func Convert_tiankuixing_UpdateConfigStatus_To_v1_UpdateConfigStatus(in *tiankuixing.UpdateConfigStatus, out *UpdateConfigStatus, s conversion.Scope) error {
	return autoConvert_tiankuixing_UpdateConfigStatus_To_v1_UpdateConfigStatus(in, out, s)
}
